vich_uploader:
  db_driver: orm
  mappings:
    produit_image:
      uri_prefix: /img/products
      upload_destination: '%kernel.project_dir%/public/img/products'
      namer: Vich\UploaderBundle\Naming\UniqidNamer
      inject_on_load: true
      delete_on_update: true
      delete_on_remove: true
    produit_image2:
      uri_prefix: /img/products
      upload_destination: '%kernel.project_dir%/public/img/products'
      namer: Vich\UploaderBundle\Naming\UniqidNamer
      inject_on_load: true
      delete_on_update: true
      delete_on_remove: true
    produit_image3:
      uri_prefix: /img/products
      upload_destination: '%kernel.project_dir%/public/img/products'
      namer: Vich\UploaderBundle\Naming\UniqidNamer
      inject_on_load: true
      delete_on_update: true
      delete_on_remove: true
